data:
  csv_path: data/raw.csv
  target: Churn
  positive_class: "Yes" # valeur positive dans la colonne cible
  test_size: 0.2
  random_state: 42

features:
  numeric: ["tenure", "MonthlyCharges", "TotalCharges"]
  categorical: [
    "gender", "SeniorCitizen", "Partner", "Dependents",
    "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity",
    "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV",
    "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod"
  ]

model:
  type: "logreg" # "logreg" ou "random_forest"
  params:
    C: [0.1, 1.0, 10.0]
    penalty: ["l2"]
    solver: ["lbfgs", "liblinear"]

cv:
  strategy: "StratifiedKFold"
  n_splits: 5
  shuffle: true
  scoring: "roc_auc"
